site_url: https://brandglue.com
# logo_url: Set this for customized CMS screen...

backend:
  name: git-gateway
  squash_merges: true

# local_backend: true

publish_mode: editorial_workflow

media_folder: static/uploads
public_folder: /uploads

collections:
  - name: blog
    label: Blog
    folder: src/content/blog
    path: '{{year}}/{{month}}/{{slug}}/index'
    slug: '{{slug}}'
    preview_path: blog/{{slug}}
    extension: mdx
    format: frontmatter
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - {
          name: date,
          label: Publish Date,
          widget: datetime,
          format: 'MMM Do YYYY',
        }
      - { name: cover_image, label: Cover Image, widget: image }
      - { name: body, label: Body, widget: markdown }
